binance:
  wss_url: wss://stream.binance.com:9443/ws
  symbols: [BTCUSDT, ETHUSDT, PEPEUSDT]
grpc:
  port: 50057
storage:
  postgres:
    dsn: postgres://postgres:postgres@localhost:5432/trading?sslmode=disable
buffers:
  tick_chan: 1000
  candle_chan: 500
health:
  data_timeout: 5m
  port: 8080